ReflectMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('reflect_me/', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "notion"
urlpatterns = [
    path('', views.MainView.as_view(), name="main"),
    path("<int:notion_id>/", views.get_notion, name="get_notion"),
    path("notions/", views.get_list_notions, name="get_notions"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("<int:notion_id>/delete", views.delete_notion, name="delete_notion"),
    path("<int:notion_id>/update", views.update_notion, name="update_notion"),
    path('add_friend/<int:friend_id>/', views.add_friend, name='add_friend'),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
    path('friends/', views.list_friends, name='list_friends'),
    path('friend_notations/<int:friend_id>/', views.friend_notations, name='friend_notations'),
    path('<int:user_id>/profile/', views.get_profile, name='get_profile'),
    path('update_profile_pic/', views.update_profile_pic, name='update_profile_pic'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Notation(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notations')
    tag_notion = models.TextField(max_length=100, default='default_value')
    topic_notion = models.TextField(max_length=100, default='default_value')
    content = models.TextField(max_length=100, default='default_value')
    created_at = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return self.topic_notion


class Friendship(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friends")
    friend = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friends_with")


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

    def __str__(self):
        return self.user.username

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Notation, UserProfile


class RequestForm(forms.Form):
    user_input = forms.CharField(label="Напиши что интересного произошло за сегодня...", max_length=100)
    is_public = forms.BooleanField(initial=False, required=False)
    tag_notion = forms.CharField(max_length=100, required=False)
    topic_notion = forms.CharField(max_length=100, required=False)


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "city",
            "password1",
            "password2",
        ]


class NotationForm(forms.ModelForm):
    class Meta:
        model = Notation
        fields = ['topic_notion', 'tag_notion', 'content', 'is_public']  # Поля, которые вы хотите включить в форму.
        widgets = {
            'topic_notion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите тему заметки'}),
            'tag_notion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите тег'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите содержимое заметки'}),
            # для чекбокса 'is_public' виджет по умолчанию подойдет, но вы можете настроить его также
        }
        labels = {
            'topic_notion': 'Тема заметки',
            'tag_notion': 'Тег',
            'content': 'Содержимое',
            'is_public': 'Публичная заметка',
        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

main_app/views.py
from django.db import transaction
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .forms import SignUpForm, RequestForm, NotationForm, UserProfileForm
from .models import Notation, Friendship, UserProfile
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("notion:main"))
        else:
            print(form.errors)
    else:
        form = SignUpForm()

    return render(request, "registration/sign_up.html", {"form": form})


class MainView(View):
    @method_decorator(login_required(login_url="/login/"))
    def get(self, request):
        form = RequestForm()
        return render(request, 'main_app/main.html', {'form': form})

    def post(self, request):
        form = RequestForm(request.POST)
        try:
            if form.is_valid():
                user_input = form.cleaned_data['user_input']
                is_public = form.cleaned_data['is_public']
                tag_notion = form.cleaned_data['tag_notion']
                topic_notion = form.cleaned_data['topic_notion']
                with transaction.atomic():
                    notion = Notation(author=request.user, content=user_input, is_public=is_public, tag_notion=tag_notion, topic_notion=topic_notion)
                    notion.save()

                return HttpResponseRedirect(reverse("main_app:get_todo", args=(notion.id,)))

                return render(request, 'main_app/main.html', {'form': form})
        except Exception as e:
            print(f"An error occurred: {str(e)}")
            return render(request, 'main_app/main.html', {'form': form})


@login_required(login_url="/login/")
def get_notion(request, notion_id):
    notion = get_object_or_404(Notation, pk=notion_id)
    context = {"notion": notion}
    return render(request, "main_app/page.html", context)


@login_required(login_url="/login/")
def get_list_notions(request):
    notions = Notation.objects.filter(author=request.user).order_by("-id")
    context = {"notions": notions}
    return render(request, "main_app/notions.html", context)


@login_required(login_url="/login/")
def delete_notion(request, notion_id):
    notion = Notation.objects.get(pk=notion_id)
    if request.method == "POST":
        if request.user == notion.author:
            notion.delete()
            return redirect(reverse("notion:get_notions"))

    context = {'main_app': notion}
    return render(request, 'main_app/notion_confirm_delete.html', context)


@login_required(login_url="/login/")
def update_notion(request, notion_id):
    notion = get_object_or_404(Notation, pk=notion_id, author=request.user)  # Получаем заметку с проверкой авторства
    if request.method == "POST":
        form = NotationForm(request.POST, instance=notion)  # Инициализация формы с текущими данными заметки
        if form.is_valid():
            form.save()  # Сохранение изменений в заметке
            return redirect(reverse("notion:get_notion", args=(notion_id,)))
    else:
        form = NotationForm(instance=notion)  # Форма для редактирования заметки

    context = {'form': form, 'notion': notion}
    return render(request, 'main_app/notion_update.html', context)  # Шаблон для обновления заметки


@login_required(login_url="/login/")
def delete_notion(request, notion_id):
    notion = Notation.objects.get(pk=notion_id)
    if request.method == "POST":
        if request.user == notion.author:
            notion.delete()
            return redirect(reverse("notion:get_notions"))

    context = {'main_app': notion}
    return render(request, 'main_app/notion_confirm_delete.html', context)


@login_required(login_url="/login/")
def get_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    context = {"user": user}
    return render(request, "main_app/profile.html", context)


@login_required
def update_profile_pic(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return redirect('notion:get_profile', user_id=request.user.id)
    else:
        form = UserProfileForm(instance=request.user.userprofile)

    return render(request, 'main_app/update_profile_pic.html', {'form': form})


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    else:
        instance.userprofile.save()


@login_required(login_url="/login/")
def add_friend(request, friend_id):
    friend = get_object_or_404(User, id=friend_id)
    request.user.add_friend(friend)
    return HttpResponseRedirect(...)


@login_required(login_url="/login/")
def remove_friend(request, friend_id):
    friend = get_object_or_404(User, id=friend_id)
    request.user.remove_friend(friend)
    return HttpResponseRedirect(...)


@login_required(login_url="/login/")
def list_friends(request):
    friends = request.user.get_friends()
    return render(request, 'friends_list.html', {'friends': friends})


@login_required(login_url="/login/")
def friend_notations(request, friend_id):
    friend = get_object_or_404(User, id=friend_id)
    notations = request.user.get_friend_notations(friend)
    return render(request, 'friend_notations.html', {'notations': notations})


def add_friend(user, friend):
    Friendship.objects.create(user=user, friend=friend)


def remove_friend(user, friend):
    Friendship.objects.filter(user=user, friend=friend).delete()


def get_friends(user):
    return User.objects.filter(friends__user=user)


def get_friend_notations(friend):
    return Notation.objects.filter(author=friend, is_public=True)

main_app/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Заголовок страницы{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>

        body {
            background-color: #f4f4f4; /* Светло-серый фон, как в Teams */
            font-family: 'Segoe UI', Arial, sans-serif; /* Шрифт Teams */
            color: #5f5f5f; /* Цвет текста */
        }

        .bg-dark-custom {
            background-color: #464775; /* Темно-синий цвет Teams */
        }

        .text-white-custom {
            color: #ffffff; /* Белый текст */
        }

        footer {
            background-color: #121212;
            padding: 2rem 0;
            background-color: #464775; /* Цвет фона футера */
            color: #ffffff; /* Цвет текста в футере */
        }

        .logo {
            color: #ffffff;
            font-weight: bold;
            font-size: 2rem;
            text-decoration: none;
        }

        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 1rem 0;
        }

        .command-button, .btn-custom {
            background-color: #6264A7;
            border: none;
            color: #ffffff;
            padding: 0.5rem 1rem;
            border-radius: 4px;
            font-size: 1rem;
        }

        .command-button:hover, .btn-custom:hover {
            background-color: #55558a; /* Темнее при наведении */
        }

        .username {
            font-weight: bold;
            font-size: 2rem;
            text-decoration: none;
        }
    </style>
</head>

<body>
    <header class="bg-dark-custom text-white-custom">
        <div class="container">
            <div class="header-content">
                <a href="{% url 'notion:main' %}" class="logo">ReflectMЕ</a>
                {% if user.is_authenticated %}
                        <a href="{% url 'notion:get_profile' user.id %}" class="text-white username"> {{ user.username }}</a>
                {% endif %}
                <div>
                    {% if user.is_authenticated %}
                        <a href="{% url 'notion:get_notions' %}" class="btn btn-outline-light btn-sm btn-custom command-button">Записи</a>
                        <a href="{% url 'logout' %}" class="btn btn-custom">Выход</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="btn btn-custom">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    <main class="py-5">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer class="bg-dark-custom text-white-custom text-center">
        <div class="container footer">
            <p>&copy; 2023 ReflectME. Все права защищены.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main_app/templates/main_app/friend_profile.html
{% extends "main_app/base.html" %}

{% block title %}Друзья пользователя{% endblock %}

{% block content %}
<main class="main">
    <div class="container mt-5" style="background-color: #ffffff; padding: 30px; border-radius: 15px; box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.5);">
        <h2 class="mb-4">Друзья</h2>
        <div class="friends-list">
            {% for friend in friends %}
                <div class="friend-card mb-4">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <h3 class="friend-name">{{ friend.username }}</h3>
                        <a href="{% url 'notion:friend_notations' friend.id %}" class="btn btn-primary">Публичные записи</a>
                        <a href="{% url 'notion:remove_friend' friend.id %}" class="btn btn-danger">Удалить из друзей</a>
                    </div>
                </div>
            {% empty %}
                <p>У вас пока нет друзей.</p>
            {% endfor %}
        </div>
    </div>
</main>

<style>
    .friend-card {
        background-color: #6264A7;
        color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.3);
    }

    .friend-name {
        font-size: 1.2em;
        margin-bottom: 5px;
    }

    .btn {
        text-decoration: none;
        padding: 10px 15px;
        border-radius: 5px;
        border: none;
        cursor: pointer;
        margin-right: 10px;
    }

    .btn-primary {
        background-color: #ff6b6b;
        color: white;
    }

    .btn-danger {
        background-color: #c0392b;
        color: white;
    }
</style>
{% endblock %}

main_app/templates/main_app/main.html
{% extends "main_app/base.html" %}

{% block title %}ReflectME{% endblock %}

{% block content %}
<main class="main">
    <div class="chat-container">
        <form action="{% url 'notion:main' %}" method="post" class="command-container">
            {% csrf_token %}

            <div class="form-group">
                <input type="text" name="tag_notion" class="form-control" id="tag-input" placeholder="Введите тег...">
            </div>

            <div class="form-group">
                <input type="text" name="topic_notion" class="form-control" id="topic-input" placeholder="Введите тему записи...">
            </div>

            <div class="form-group">
                <textarea name="user_input" class="form-control command-input" id="user-input" placeholder="Введите текст записи..." rows="3"></textarea>
            </div>

            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="public-private-toggle" name="is_public">
                <label class="form-check-label" for="public-private-toggle">Сделать запись публичной</label>
            </div>

            <button type="submit" class="command-button">Отправить</button>
        </form>

        {% if form.errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
</main>
{% endblock %}

main_app/templates/main_app/notion_confirm_delete.html
{% extends "main_app/base.html" %}

{% block title %}Подтверждение удаления{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="mb-4">Вы действительно хотите удалить "{{ todo.title }}"?</h2>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'notion:get_notions' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

main_app/templates/main_app/notion_update.html
{% extends "main_app/base.html" %}

{% block title %}Редактирование заметки{% endblock %}

{% block content %}
<main class="main">
    <div class="container mt-5">
        <h2 class="mb-4">Редактирование заметки</h2>
        <form action="{% url 'notion:update_notion' notion.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="topic_notion">Тема заметки:</label>
                <input type="text" name="topic_notion" class="form-control" id="topic_notion" value="{{ notion.topic_notion }}">
            </div>
            <div class="form-group">
                <label for="tag_notion">Тег:</label>
                <input type="text" name="tag_notion" class="form-control" id="tag_notion" value="{{ notion.tag_notion }}">
            </div>
            <div class="form-group">
                <label for="content">Содержимое:</label>
                <textarea name="content" class="form-control" id="content" rows="5">{{ notion.content }}</textarea>
            </div>
            <div class="form-check mb-3">
                <input type="checkbox" name="is_public" class="form-check-input" id="is_public" {% if notion.is_public %}checked{% endif %}>
                <label for="is_public" class="form-check-label">Публичная заметка</label>
            </div>
            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            <a href="{% url 'notion:get_notion' notion.id %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
</main>
{% endblock %}

main_app/templates/main_app/notions.html
{% extends "main_app/base.html" %}

{% block title %}Список заметок{% endblock %}

{% block content %}
<main class="main">
        <div class="container mt-5">
            <h2 class="mb-4">Список заметок</h2>
            <div class="book">
                <div class="book-pages">
                   {% for note in notions %}
                        <div class="book-page">
                            <h5 class="book-title">{{ note.topic_notion }}</h5>
                            <h6 class="book-tag">{{ note.tag_notion }}</h6>
                            <a href="{% url 'notion:get_notion' note.id %}" class="btn">Подробнее</a>
                            <a href="{% url 'notion:delete_notion' note.id %}" class="btn btn-danger">Удалить</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
</main>

<style>

    .notation-privacy-status {
        background-color: #007bff;
        color: white;
        padding: 5px;
        border-radius: 5px;
        position: absolute;
        bottom: 10px;
        right: 10px;
        font-size: 0.8em;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
    }

    .book {
        background-color: #f4f4f4;
        border-radius: 15px;
        box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.5);
        padding: 20px;
    }

    .book-pages {
        position: relative;
        display: flex;
        flex-direction: column;
    }

    .book-page {
        background-color: #464775;
        color: white;
        margin-bottom: 20px;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.3);
    }

    .book-title {
        font-size: 1.2em;
        margin-bottom: 15px;
    }

    .btn {
        display: inline-block;
        margin-right: 10px;
        padding: 5px 10px;
        border: none;
        border-radius: 5px;
        background-color: #ff6b6b;
        color: white;
        cursor: pointer;
    }

    .book-tag {
        opacity: 0.75; /* Увеличивает видимость (меньше прозрачности) */
        font-size: smaller; /* Меньший размер шрифта по сравнению с book-title */
        color: #fff; /* Цвет текста, можно настроить */
        margin-top: -15px; /* Минимальный отступ сверху, чтобы приблизить к book-title */
    }

    .btn-danger {
        background-color: #c0392b;
    }

</style>
{% endblock %}

main_app/templates/main_app/page.html
{% extends "main_app/base.html" %}

{% block title %}ReflectME{% endblock %}

{% block content %}
<main class="main">
    <div class="container mt-5" style="background-color: #ffffff; padding: 30px; border-radius: 15px; box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.5);">
        <div class="notation-card mb-4">
            <div class="d-flex justify-content-between align-items-center mb-2">
                <div>
                    <h3 class="notation-title">{{ notion.topic_notion }}</h3>
                    <!-- Кнопка редактирования рядом с заголовком темы -->
                    <a href="{% url 'notion:update_notion' notion.id %}" class="btn btn-primary">Изменить</a>
                </div>
                <span class="notation-tag">{{ notion.tag_notion }}</span>
            </div>
            <p class="notation-author">Автор: {{ notion.author.username }}</p>
            <p class="notation-content">{{ notion.content }}</p>
            <p class="notation-date">Создано: {{ notion.created_at|date:"d.m.Y H:i" }}</p>
            <a href="{% url 'notion:delete_notion' notion.id %}" class="btn btn-danger">Удалить</a>
            <div class="notation-privacy-status">
                {{ notion.is_public|yesno:"Публичная,Приватная" }}
            </div>
        </div>
    </div>
</main>

<style>

    .notation-card {
        background-color: #6264A7;;
        padding: 20px;
        border-radius: 10px;
        color: white;
        box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.5);
    }

    .notation-title {
        color: #ff9900;
        margin-bottom: 5px;
    }

    .notation-tag {
        background-color: #007bff;
        color: white;
        padding: 3px 8px;
        border-radius: 5px;
        font-size: 0.9em;
    }

    .notation-author {
        font-style: italic;
        margin-bottom: 10px;
    }

    .notation-content {
        margin-bottom: 10px;
    }

    .notation-date {
        font-size: 0.8em;
        color: #aaa;
    }

   .notation-privacy-status {
        background-color: #007bff; /* Синий фон для публичной, измените цвет при необходимости */
        color: white;
        padding: 10px;
        border-radius: 5px; /* Закругленные углы для куба */
        position: absolute; /* Абсолютное позиционирование внутри notation-card */
        bottom: 10px; /* Отступ снизу */
        right: 10px; /* Отступ справа вместо слева */
        font-size: 0.8em;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5); /* Добавление тени для эффекта "куба" */
    }

    .notation-card {
        position: relative; /* Для позиционирования .notation-privacy-status */
        /* Остальные стили */
    }

    .btn {
        background-color: #ff6b6b;
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        margin-right: 10px;
    }

    .btn-danger {
        background-color: #c0392b;
    }

</style>
{% endblock %}

main_app/templates/main_app/profile.html
{% extends "main_app/base.html" %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<main class="main">
    <div class="container mt-5" style="background-color: #ffffff; padding: 30px; border-radius: 15px; box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.5);">
        <div class="user-profile d-flex justify-content-between">
            <div class="profile-info">
                <h2 class="mb-4">{{ user.username }}'s Профиль</h2>
                <p>Имя: {{ user.first_name }}</p>
                <p>Фамилия: {{ user.last_name }}</p>
                <p>Email: {{ user.email }}</p>
            </div>
            <div class="profile-pic">
                {% if user.userprofile.profile_pic %}
                    <img src="{{ user.userprofile.profile_pic.url }}" alt="Profile Picture" style="max-width: 150px; max-height: 150px; border-radius: 50%;">
                {% else %}
                    <p>Фотография профиля не загружена.</p>
                {% endif %}
                <a href="{% url 'notion:update_profile_pic' %}" class="btn btn-info mt-3">Изменить фото</a>
            </div>
        </div>
    </div>
</main>

<style>
    .user-profile {
        background-color: #6264A7;
        color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.3);
    }

    .profile-info {
        /* Стили для информации профиля */
    }

    .profile-pic {
        /* Стили для блока с фотографией профиля */
    }

    .btn {
        text-decoration: none;
        padding: 10px 15px;
        border-radius: 5px;
        border: none;
        cursor: pointer;
        margin-right: 10px;
        margin-bottom: 10px;
    }

    .btn-primary {
        background-color: #ff6b6b;
        color: white;
    }

    .btn-info {
        background-color: #17a2b8;
        color: white;
    }
</style>
{% endblock %}

main_app/templates/main_app/update_profile_pic.html
{% extends "main_app/base.html" %}

{% block title %}Изменить фото профиля{% endblock %}

{% block content %}
<main class="main">
    <div class="container mt-5" style="background-color: #ffffff; padding: 30px; border-radius: 15px; box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.5);">
        <h2 class="mb-4">Изменить фото профиля</h2>
        <form action="{% url 'notion:update_profile_pic' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_profile_pic">Выберите изображение:</label>
                {{ form.profile_pic }}
            </div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'notion:get_profile' user.id %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
</main>

<style>
    .form-group {
        margin-bottom: 15px;
    }

    .btn {
        padding: 10px 15px;
        border-radius: 5px;
        border: none;
        cursor: pointer;
        margin-right: 10px;
        text-decoration: none;
    }

    .btn-primary {
        background-color: #ff6b6b;
        color: white;
    }

    .btn-secondary {
        background-color: #6264A7;
        color: white;
    }
</style>
{% endblock %}